config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists do
    resources :items do
    	member do
    		patch :complete
        patch :put
    	end
    end
  end
 root "lists#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
	validates :content, presence: true


  def completed?
  	!completed_at.blank?
  end

  def puted?
  	!puted_at.blank?
  end
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items
	validates :title, presence: true
	belongs_to :user

	def self.search(search)
	  where(" title LIKE ?", "%#{search}%")
	end
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_list
	before_action :set_item, except: [:create]

	def create
		@item = @list.items.create(items_params)
		redirect_to @list
	end

	def destroy
		@item = @list.items.find(params[:id])
		if @item.destroy
			flash[:success] = "La tâche a été supprimée."
		else 
			flash[:error] = "La tâche ne peut être supprimée"
		end
		redirect_to @list
	end

	def complete
		@item.update_attribute(:completed_at, Time.now)
		redirect_to @list, notice: "Tâche effectuée"
	end

	def put
		@item.update_attribute(:puted_at, Time.now)
		redirect_to @list, notice: "Item puted"
	end

	private

	def set_list
		@list = List.find(params[:list_id])
	end

	def set_item
		@item = @list.items.find(params[:id])
	end

	def items_params
		params.require(:item).permit(:content)
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    if params[:search]
      @lists = List.search(params[:search]).paginate(:page => params[:page], :per_page => 6).order("created_at DESC")
    else
      @lists = List.paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
 
  end

  # GET /lists/new
  def new
    @list = List.new
  end


  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.build(params[:list].permit(:title, :description))

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'Liste créée avec succès.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'Liste modifiée avec succes' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Liste supprimée avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for ([@list, @list.items.build]) do |f| %>
	<%= f.text_field :content, placeholder: "Nouvelle tâche" %>
	<%= f.submit "Nouvelle tâche" %>
<% end %>

app/views/items/_item.html.erb
<div class="row clearfix">
	<% if item.completed? %>
		<div class="complete">
			<i style="opacity: 0.5;" class="fa fa-check"></i>
		</div>
		<div class="todo_item">
			<p style="opacity: 0.5;"><strike><%= item.content %></strike></p>
		</div>
		<div class="trash">
		<% if @list.user == current_user %>
			<%= link_to list_item_path(@list, item.id), method: :delete, data: { confirm: "Etes vous sûr?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		<% end %>
		</div>
	<% else %>
		<div class="complete">
		<% if @list.user == current_user %>
			<%= link_to complete_list_item_path(@list, item.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		<% end %>
		</div>
		<div class="todo_item">
			<p><%= item.content %></p>
		</div>
		<div class="trash">
		<% if @list.user == current_user %>
			<%= link_to list_item_path(@list,item.id), method: :delete, data: { confirm: "Etes vous sûr?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		<% end %>
		</div>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<% unless user_signed_in? %>
<div class="col-md-2 pull-right icon">
	<%= link_to "",user_session_path , class:"fa fa-user"%>	
</div>
<% else %>
<div class="col-md-2 pull-right icon">
	<%= link_to "",destroy_user_session_path , :method => :delete,class:"fa fa-power-off"%>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <link rel="icon" href="images/logo.jpg" />
  <meta http-equiv="content-language" content="en"/>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width"/>
  <meta name="description" content="Simple ToDo List pour ne plus oublier se que vous devez faire !">
    <meta name="author" content="Linda LOR">
    <meta name="keywords" content="Todo, list, Linda, LOR, web, rubyonrails">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= stylesheet_link_tag    'bootstrap' %>
  <%= stylesheet_link_tag    'style' %>
 
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1 class="todo_list_title">Modifier liste</h1>

<div class="forms">
	<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit "Liste modifiée" %>
  </div>
<% end %>
</div>

<div class="links">
	<%= link_to 'Annuler', lists_path %>
</div>	

app/views/lists/index.html.erb
 <% if user_signed_in? %>
  <h2 class="welcome">Bienvenu <%= current_user.username %></h2>
  <% else %>
  <h3 class="welcome2">Connectez-vous pour créer une liste</h3>
 <% end %>

  <form action="" class="search-form">
    <div class="form-group">
        <%= form_tag(lists_path, :method => "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Chercher le titre de la liste", id:"search",class: "form-control" %>
        <% end %>
    </div>
  </form>

<div class="row">
<div class="col-md-12">
<p id="notice"><%= notice %></p>
<% if @lists.present?%>
<%  @lists.each do |list | %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"> <%= link_to list.title, list %></h2>
    <small><em>Liste de: <%= list.user.username unless list.user.blank? %><em></small>
  </div>
<% end %>
<% else %>
  <p>Il n'y a pas de liste contenant le(s) terme(s) <%= params[:search] %>.</p>
  <div class="links">
  <%= link_to "Retour",lists_path %>
  </div>
<% end %>
</div>
</div>
<div class="links">
 <%= will_paginate @lists, renderer: BootstrapPagination::Rails,  :previous_label => 'Précédent', :next_label => 'Suivant' %>
  <%= link_to "Nouvelle liste", new_list_path %>
  <%= render 'layouts/footer' %>
</div>

app/views/lists/new.html.erb
<h1 class="todo_list_title">Nouvelle liste</h1>

<div class="forms">
	<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit "Nouvelle liste" %>
  </div>
<% end %>
</div>

<div class="links">
	<%= link_to 'Retour', lists_path %>
</div>	

app/views/lists/show.html.erb
<h2 class="todo_list_title"><%= @list.title %></h2>
<p id="notice"><%= notice %></p>
<div id="todo_items_wrapper">
	<%= render @list.items %>
	<% if @list.user == current_user %>
	<div id="form">
		<%= render "items/form" %>
	</div>
	<% end %>
</div>

<div class="links">
<% if @list.user == current_user %>
	<%= link_to 'Modifier', edit_list_path(@list) %> |
	<%= link_to 'Supprimer', list_path(@list), method: :delete, data: {confirm: "Etes vous sûr?"} %>|
<% end %>
	<%= link_to 'Retour', lists_path %>
</div>